### ISSUE TITLE
Remove unneeded dependencies (in SNAPSHOT branch)

### ISSUE THREAD

**Issue by gslowikowski** [playframework/play-scala-macwire-di-example#21]
These two are not used:
```scala
libraryDependencies += guice
libraryDependencies += ws % Test // only used in tests right now
```
(https://github.com/playframework/play-macwire-di/blob/1557c85337dd258c80e035711b58f1aa123aa2e0/build.sbt#L9-L10)

I don't know Macwire, but application seems to work properly without these two:
```scala
libraryDependencies += "com.softwaremill.macwire" %% "util" % "2.3.0"
libraryDependencies += "com.softwaremill.macwire" %% "proxy" % "2.3.0"
```
(https://github.com/playframework/play-macwire-di/blob/1557c85337dd258c80e035711b58f1aa123aa2e0/build.sbt#L13-L14)

**Comment by wsargent** [comment]
Fixed by https://github.com/playframework/play-scala-macwire-di-example/pull/35
