### ISSUE TITLE
Cannot resolve symbol router

### ISSUE THREAD

**Issue by raul782** [playframework/play-scala-macwire-di-example#4]
When reviewing the Application Loader
https://github.com/playframework/play-macwire-di/blob/master/app/GreetingApplicationLoader.scala#L8
with IntelliJ
If you try to run the project, you get an error related to the import statement.
You have to go to the target folder and Cancel Exclusion then Mark as Generated Sources
It seems you have to do this every time the project is re-imported, is there a way to improve the DX

@gmethvin

**Comment by ghost** [comment]
hm but it still doesnt fix it anyway?
